module.exports = {
  limit: [
    {symbol:'DEI',full_name:'DEI',description:'Douglas Emmett Inc',exchange:'NYSE',type:'stock'},{symbol:'^GDAXI',full_name:'^GDAXI',description:'DAX',exchange:'XETRA',type:'index'},
    {symbol:'XINA50',full_name:'XINA50',description:'A50',exchange:'SGX',type:'futures'},
    {symbol:'AA',full_name:'AA',description:'Alcoa Inc.',exchange:'NYSE',type:'stock'},
    {symbol:'AAL',full_name:'AAL',description:'American Inc.',exchange:'NasdaqNM',type:'stock'},
    {symbol:'AAPL',full_name:'AAPL',description:'Apple Inc.',exchange:'NasdaqNM',type:'stock'},
    {symbol:'ABB',full_name:'ABB',description:'ABB Ltd.',exchange:'NYSE',type:'stock'},
    {symbol:'ABBV',full_name:'ABBV',description:'AbbVie Inc.',exchange:'NYSE',type:'stock'},
    {symbol:'ABT',full_name:'ABT',description:'Abbott Laboratories',exchange:'NYSE',type:'stock'},
    {symbol:'ABX',full_name:'ABX',description:'Barrick Gold Corporation',exchange:'NYSE',type:'stock'},
    {symbol:'ACHN',full_name:'ACHN',description:'Achillion Inc.',exchange:'NasdaqNM',type:'stock'},
    {symbol:'ACI',full_name:'ACI',description:'Arch Coal Inc.',exchange:'NYSE',type:'stock'},
    {symbol:'ACN',full_name:'ACN',description:'Accenture plc',exchange:'NYSE',type:'stock'},
    {symbol:'ACT',full_name:'ACT',description:'Actavis plc',exchange:'NYSE',type:'stock'},
    {symbol:'ADBE',full_name:'ADBE',description:'Adobe Systems Inc.',exchange:'NasdaqNM',type:'stock'},
    {symbol:'ADSK',full_name:'ADSK',description:'Autodesk, Inc.',exchange:'NasdaqNM',type:'stock'},
    {symbol:'AEO',full_name:'AEO',description:'Outfitters, Inc.',exchange:'NYSE',type:'stock'},
    {symbol:'AGNC',full_name:'AGNC',description:' Agency Corp.',exchange:'NasdaqNM',type:'stock'},
    {symbol:'AIG',full_name:'AIG',description:'International Group, Inc.',exchange:'NYSE',type:'stock'},
    {symbol:'AKAM',full_name:'AKAM',description:'Technologies, Inc.',exchange:'NasdaqNM',type:'stock'},
    {symbol:'ALU',full_name:'ALU',description:'Alcatel-Lucent',exchange:'NYSE',type:'stock'},
    {symbol:'ALXN',full_name:'ALXN',description:'Pharmaceuticals Inc.',exchange:'NasdaqNM',type:'stock'},
    {symbol:'AMAT',full_name:'AMAT',description:'Materials, Inc.',exchange:'NasdaqNM',type:'stock'},
    {symbol:'AMD',full_name:'AMD',description:'Micro Devices, Inc.',exchange:'NYSE',type:'stock'},
    {symbol:'AMGN',full_name:'AMGN',description:'Amgen Inc.',exchange:'NasdaqNM',type:'stock'},
    {symbol:'AMZN',full_name:'AMZN',description:'Amazon.com Inc.',exchange:'NasdaqNM',type:'stock'},
    {symbol:'ANF',full_name:'ANF',description:'Abercrombie & Fitch Co.',exchange:'NYSE',type:'stock'},
    {symbol:'ANR',full_name:'ANR',description:'Resources, Inc.',exchange:'NYSE',type:'stock'},
    {symbol:'APA',full_name:'APA',description:'Apache Corp.',exchange:'NYSE',type:'stock'},
    {symbol:'APC',full_name:'APC',description:'Petroleum Corporation',exchange:'NYSE',type:'stock'}
  ],
  marks: {
    id:[0,1,2,3,4,5],
    time:[1455148800,1455235200,1454976000,1454976000,1454284800,1452988800],
    color:["red","blue","green","red","blue","green"],
    text:["今天1","测试2","测试3","测试4","测试5","测试6"],
    label:["A","B","CORE","D","EURO","F"],
    labelFontColor:["white","white","red","#FFFFFF","white","#000"],
    minSize:[14,28,7,40,7,14]
  }
}